# Change these first
owner: codextde # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Codext Website
    url: https://codext.de/
  - name: Codext Analytics
    url: https://analytics.codext.de/
  - name: Codext Link
    url: https://codext.link/
  - name: Codext Server - Server01
    url: https://server01.codext.de:8443/
  - name: Codext Server - Lara
    url: https://lara.codext.de:8006/
#  - name: Codext Server - Adeo
#    url: https://adeo.codext.de:8006/
#  - name: Codext Server - Lina
#    url: https://lina.codext.de:8006/
#  - name: Codext Openreplay
#    url: https://openreplay.codext.de/
#  - name: Codext Dashboard
#    url: https://dashboard.codext.de/
  - name: Webaro Cloud
    url: https://webaro.cloud/
  - name: Codext Sentry
    url: https://sentry.codext.de/
  - name: Codext Cloud
    url: https://codext.cloud/
  - name: convertAny
    url: https://convert-any.com/
#  - name: deinkind.store
#    url: https://deinkind.store/
  - name: PayStory API
    url: https://api.paystory.de/
  - name: Smartbell API
    url: https://api.smartbell.codext.de/v1
#  - name: Smartbell DB 
#    check: "tcp-ping"
#    url: 167.235.158.98
#    port: 27017
  - name: WeTwo API
    url: https://api.we-two.de/apple-app-site-association
#  - name: Codext Shopify Apps API
#    check: "tcp-ping"
#    url: 49.13.16.142
    port: 22
  - name: Codext Customer 1
    check: "tcp-ping"
    url: 168.119.226.168
    port: 22
#  - name: Codext Coturn
#    check: "tcp-ping"
#    url: 49.13.54.252
#    port: 80
#  - name: Codext Rustdesk Public Server
#    check: "tcp-ping"
#    url: 88.99.224.152
#    port: 21115
#  - name: Shopify Checkout
#    url: https://sportnahrung-wehle.de/67705798956/checkouts/2796f5ffc00ed9db3595d418dba9cdb2
  - name: GGM Gastro DK
    url: https://ggmgastro.dk/
  - name: GGM Gastro NO
    url: https://ggmgastro.no/
  - name: GGM SAP Export
    url: https://ggm-sap-sync.codext.de
  - name: Shopify Chatbot
    url: https://shopify-chatbot.codext.de/
#  - name: SirPlus Konfigurator
#    url: https://sirplusconfig.codext.de
  - name: Codext GmbH - Coolify
    url: https://coolify.codext.de/
  - name: Solakon App API
    url: https://api.app.solakon.de
  - name: Solakon App DB
    url: https://db.app.solakon.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Codext Uptime
  introTitle: "Uptime monitor and status page"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
